name: Syntax Check

on:
  push:
    paths:
      - rules/**
      - .github/workflows/syntax_check.yaml

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    container:
      image: falcosecurity/falco:latest
      volumes:
        - ${{ github.workspace }}:/workspace:ro
      options: --cpus 1
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Syntax check
        run: |
          falco -V /etc/falco/falco_rules.yaml \
                -V /workspace/rules/access_rules.yaml
